### ISSUE TITLE
Android 7.0显示问题

### ISSUE THREAD

**Issue by Missyouag** [RuffianZhong/RVPIndicator#1]
Android 7.0 view优化，导致onSizeChanged添加view不显示问题。

**Comment by RuffianZhong** [comment]
@Missyouag 
解决：addView之前重新测量一下父布局控件宽高
` private void initTabItem() {
        if (mTabTitles != null && mTabTitles.size() > 0) {
            //省略代码...
            for (String title : mTabTitles) {
                measure(0, 0);//重新测量宽高
                addView(createTextView(title));
            }
            //省略代码...
        }
    }`
2.同时在第二个构造函数中添加内容水平居中代码
`public RVPIndicator(Context context, AttributeSet attrs) {
        super(context, attrs);
        setGravity(Gravity.CENTER_VERTICAL);
        //省略代码...
    }`

**Comment by rainbeanFan** [comment]
Vivo  X9s Plus   初次进入界面时最后一个标题占位不显示，滑动一下才能显示

**Comment by RuffianZhong** [comment]
@rainbeanFan 我这边就找到一个Vivo X9  版本7.1.1 的手机，测试了，没有看到你说的BUG，很尴尬，但是确实还有人说有这个BUG，能麻烦你提供多一点信息嘛？或者你看看会是哪里引起的？

**Comment by rainbeanFan** [comment]
同7.1.1版本，真机被拿走了。今天在模拟器上也出现了这个问题，模拟器信息Android 8.0  X86

**Comment by RuffianZhong** [comment]
@rainbeanFan 我安装了模拟器 Android 8.0 X86 还是没有复现，但我觉得应该是有问题的，你加我QQ:632835821（我无法添加你好友）

**Comment by RuffianZhong** [comment]
@rainbeanFan 已经修复，更新版本至1.0.4
