### ISSUE TITLE
线的高度不能自定义？

### ISSUE THREAD

**Issue by for7GG** [RuffianZhong/RVPIndicator#2]
当风格为Line时，感觉线的高度太高，最好能增加自定义选项

**Comment by RuffianZhong** [comment]
@jielundewode 
现在下划线高度是指示器高度的 1/10 。
`mIndicatorHeight = h / 10;`
如果项目急用，你可以自己修改，稍后我会把自定义高度的功能加上。

**Comment by for7GG** [comment]
@RuffianZhong 谢谢解答，我已经修改了，项目不错，只是一个建议，方便定制，辛苦了！

**Comment by RuffianZhong** [comment]
更新版本至1.0.4可自定义指示器高度（下划线模式才有效）
