### ISSUE TITLE
在华为手机上最后一个标题显示不出来

### ISSUE THREAD

**Issue by for7GG** [RuffianZhong/RVPIndicator#3]
在华为手机上最后一个标题显示不出来（华为荣耀手机 android7.0系统）

**Comment by RuffianZhong** [comment]
@jielundewode 就最后一个标题显示不出来？之前android 7.0以上不能绘制，你参考下[#1](https://github.com/RuffianZhong/RVPIndicator/issues/1)

**Comment by RuffianZhong** [comment]
@jielundewode 已经修复，更新版本至1.0.4
