### ISSUE TITLE
倒过来的三角形指示器怎么画？

### ISSUE THREAD

**Issue by wcglws** [RuffianZhong/RVPIndicator#4]
以三角形底边做个镜像，就是三角形尖头顶点朝下，该怎么画？请大神指点

**Comment by RuffianZhong** [comment]
@wcglws 
这个很简单，你应该去看懂代码然后自己去实现。这里还是给出实现
dispatchDraw(Canvas canvas) > case STYLE_TRIANGLE:  > (把之前绘制三角形的代码改为如下代码即可)
                mPath.moveTo(midOfTab, getHeight());
                mPath.lineTo(midOfTab - mIndicatorWidth / 2, getHeight()- mIndicatorHeight);
                mPath.lineTo(midOfTab + mIndicatorWidth / 2, getHeight()- mIndicatorHeight);

**Comment by wcglws** [comment]
大神没有理解我的意思，我说的是下面这种效果
![20171204160300](https://user-images.githubusercontent.com/16982083/33542137-b275deca-d90c-11e7-971d-8eab088f66c8.png)

**Comment by RuffianZhong** [comment]
@wcglws 
这种效果，你可以在理解这个源码的基础上自己去实现一下
（滑动那部分逻辑可以直接用）将倒三角形的位置在竖直方向上提高一定的高度，底部视图可以设置颜色。这样的效果就是你自己的了，实现出来不是很有收获？

**Comment by wcglws** [comment]
不是太懂你的意思，倒三角和tab分开画么？tab的height是固定的，按照你原来的思路，把三角形画高一点，就会被tab截断，显示不全；底部视图以何种方式设置颜色？楼主不要误解，是不是伸手党见多了？

**Comment by RuffianZhong** [comment]
@wcglws 
三角形也是画view的一部分，如若要实现你这种效果思路是：在画三角形之前先画下面灰色的矩形，然后在上面画三角形，滑动的时候只需要移动三角形，对于title你可以不要居中（这个微调一下）应该可以实现。

**Comment by wcglws** [comment]
好的，谢谢
